diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.autocrlf=true
user.name=t2212605
user.email=t2212605@partner.coway.com
difftool.sourcetree.cmd='' 
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
credential.https://git-codecommit.ap-northeast-2.amazonaws.com.provider=generic
safe.directory=D:/project/IoCareAPP_Git
safe.directory=C:/Users/mcnc/Documents/cw-iocare-contents
safe.directory=C:/Users/mcnc/Documents/CodyApp-Web
http.sslverify=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=jkh8360
user.email=jkh8360@gmail.com
remote.origin.url=https://github.com/jkh8360/autoCoin.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
